name: nx build
on:
  push:
    branches:
      - dev
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Nx set SHAs
      - uses: nrwl/nx-set-shas@v2.0.2

      - run: yarn install --frozen-lockfile
      - run: yarn nx workspace-lint
      - run: yarn nx format:check
      - run: yarn nx affected --target=lint --parallel=3
      - run: yarn nx affected --target=test --parallel=3 --ci --code-coverage
      - run: yarn nx affected --target=build --parallel=3
